// Generated by CoffeeScript 1.7.1
(function() {
  window.backgroundCanvas = null;

  window.createBackgroundCanvas = function(daytime) {
    var buildingPosition, context, height, i, light_chance, size, storey, storeys, x, y, _i, _j, _k, _l, _ref, _results;
    if (daytime == null) {
      daytime = true;
    }
    window.backgroundCanvas = createCanvas(BACKGROUND_WIDTH, CANVAS_HEIGHT);
    context = backgroundCanvas.getContext("2d");
    context.fillStyle = daytime ? Colour.DAY_SKY : Colour.NIGHT_SKY;
    context.fillRect(0, 0, BACKGROUND_WIDTH, SCREEN_HEIGHT);
    context.fillStyle = Colour.GROUND;
    context.fillRect(0, SCREEN_HEIGHT, BACKGROUND_WIDTH, GROUND_GRASS_HEIGHT);
    context.fillStyle = Colour.PIPE;
    context.fillRect(0, SCREEN_HEIGHT + GROUND_GRASS_HEIGHT, BACKGROUND_WIDTH, GROUND_HEIGHT - GROUND_GRASS_HEIGHT);
    if (!daytime) {
      context.fillStyle = Colour.STAR;
      for (i = _i = 0; 0 <= STAR_COUNT ? _i < STAR_COUNT : _i > STAR_COUNT; i = 0 <= STAR_COUNT ? ++_i : --_i) {
        x = randomNumberExclusive(0, BACKGROUND_WIDTH);
        y = randomNumberExclusive(MIN_STAR_HEIGHT, MAX_STAR_HEIGHT);
        size = randomNumberInclusive(1, STAR_MAX_SIZE);
        context.beginPath();
        context.arc(x, y, size, 0, 2 * Math.PI);
        context.fill();
      }
    }
    buildingPosition = 0;
    light_chance = daytime ? BUILDING_LIGHT_ON_DAY_CHANCE : BUILDING_LIGHT_ON_NIGHT_CHANCE;
    _results = [];
    while (buildingPosition < BACKGROUND_WIDTH) {
      if (Math.random() < BUILDING_HERE_CHANCE) {
        storeys = randomNumberInclusive(BUILDING_MIN_STOREYS, BUILDING_MAX_STOREYS);
        height = storeys * BUILDING_STOREY_HEIGHT;
        context.fillStyle = Colour.BUILDING;
        context.fillRect(buildingPosition, SCREEN_HEIGHT - height, BUILDING_WIDTH, height);
        for (storey = _j = 1, _ref = storeys + 1; 1 <= _ref ? _j < _ref : _j > _ref; storey = 1 <= _ref ? ++_j : --_j) {
          for (x = _k = 0; 0 <= BUILDING_WINDOWS_WIDE ? _k < BUILDING_WINDOWS_WIDE : _k > BUILDING_WINDOWS_WIDE; x = 0 <= BUILDING_WINDOWS_WIDE ? ++_k : --_k) {
            for (y = _l = 0; 0 <= BUILDING_WINDOWS_HIGH ? _l < BUILDING_WINDOWS_HIGH : _l > BUILDING_WINDOWS_HIGH; y = 0 <= BUILDING_WINDOWS_HIGH ? ++_l : --_l) {
              if (Math.random() < light_chance) {
                context.fillStyle = Colour.BUILDING_LIGHT_ON;
              } else {
                context.fillStyle = Colour.BUILDING_LIGHT_OFF;
              }
              context.fillRect(buildingPosition + (BUILDING_WINDOW_WIDTH / 2) + (x * BUILDING_WINDOW_WIDTH * 2), SCREEN_HEIGHT - (storey * BUILDING_STOREY_HEIGHT) + (BUILDING_WINDOW_HEIGHT / 2) + (y * BUILDING_WINDOW_HEIGHT * 2), BUILDING_WINDOW_WIDTH, BUILDING_WINDOW_HEIGHT);
            }
          }
        }
      }
      _results.push(buildingPosition += BUILDING_WIDTH);
    }
    return _results;
  };

}).call(this);
