// Generated by CoffeeScript 1.7.1
(function() {
  window.Colour = {
    DAY_SKY: "#00bbff",
    NIGHT_SKY: "#000000",
    GROUND: "#00ff00",
    PLAYER: "#ffff00",
    PLAYER_STRIPE: "#000000",
    PIPE: "#8b4513",
    COLLISION: "#0000ff",
    TEXT: "#000000",
    TEXT_BACKGROUND: "#ffffff",
    BUTTON_HOVER_BACKGROUND: "#cccccc",
    BUILDING: "#646464",
    BUILDING_LIGHT_ON: "#ffff00",
    BUILDING_LIGHT_OFF: "#101010",
    STAR: "#ffffff"
  };

}).call(this);
