window.GAME_NAME = "BUZZY_BEE"
window.GAME_VERSION_MAJOR = 1
window.GAME_VERSION_MINOR = 0
window.GAME_VERSION = "#{GAME_VERSION_MAJOR}.#{GAME_VERSION_MINOR}"

window.CANVAS_WIDTH = 720
window.CANVAS_HEIGHT = 512
window.CANVAS_BORDER_THICKNESS = 1
window.GROUND_HEIGHT = CANVAS_HEIGHT * 0.2
window.SCREEN_HEIGHT = CANVAS_HEIGHT - GROUND_HEIGHT
window.GROUND_GRASS_HEIGHT = Math.floor(GROUND_HEIGHT * 0.3)

window.OUTLINE_THICKNESS = 2



window.DAYTIME_CHANCE = 0.8
window.BACKGROUND_PARALLAX = 0.2
window.BUILDING_WIDTH = Math.floor(CANVAS_WIDTH * 0.04)
window.BUILDING_COUNT = 50
window.BACKGROUND_WIDTH = BUILDING_WIDTH * BUILDING_COUNT
window.BUILDING_STOREY_HEIGHT = SCREEN_HEIGHT * 0.05
window.BUILDING_MIN_STOREYS = 1
window.BUILDING_MAX_STOREYS = 12
window.BUILDING_HERE_CHANCE = 0.7
window.BUILDING_LIGHT_ON_DAY_CHANCE = 0.1
window.BUILDING_LIGHT_ON_NIGHT_CHANCE = 0.8
window.BUILDING_WINDOWS_WIDE = 2
window.BUILDING_WINDOWS_HIGH = 1
window.BUILDING_WINDOW_WIDTH = Math.floor(BUILDING_WIDTH / (2 * BUILDING_WINDOWS_WIDE))
window.BUILDING_WINDOW_HEIGHT = Math.floor(BUILDING_STOREY_HEIGHT / (2 * BUILDING_WINDOWS_HIGH))
window.MIN_STAR_HEIGHT = SCREEN_HEIGHT * 0
window.MAX_STAR_HEIGHT = SCREEN_HEIGHT * 0.35
window.STAR_COUNT = 100
window.STAR_MAX_SIZE = 2



window.PLAYER_WIDTH = 24
window.PLAYER_HEIGHT = 24
window.PLAYER_START_X = Math.floor(CANVAS_WIDTH * 0.2)
window.PLAYER_START_Y = Math.floor((SCREEN_HEIGHT * 0.5) - (PLAYER_HEIGHT / 2))
window.PLAYER_STRIPE_COUNT = 4
window.PLAYER_STRIPE_WIDTH = Math.floor(PLAYER_WIDTH / (2.5 * PLAYER_STRIPE_COUNT))
window.PLAYER_EYE_SIZE = 4
window.PLAYER_EYE_BORDER = 2
window.PLAYER_JUMP_ROTATION = -30
window.PLAYER_MAX_ROTATION = 35
window.PLAYER_ROTATION_SPEED = 80
window.PLAYER_TRAIL_THICKNESS = 2
window.PLAYER_AI_MIN_Y_DIFFERENCE = -10




window.GRAVITY = 700
window.JUMP_VELOCITY = -260



window.PIPE_COUNT = 10
window.PIPE_GAP_HORIZONTAL = Math.floor(CANVAS_WIDTH * 0.21)
window.PIPE_WIDTH = Math.floor(CANVAS_WIDTH * 0.055)
window.PIPE_GAP_HEIGHT = Math.floor(SCREEN_HEIGHT * 0.21)
window.PIPE_MIN_HEIGHT = Math.floor(SCREEN_HEIGHT * 0.1)
window.START_PIPE_X = Math.floor(CANVAS_WIDTH * 1.05)

window.MOVE_SPEED = 120



window.GAME_SCORE_X = 15
window.GAME_SCORE_Y = 15
window.GAME_SCORE_EXTRA_WIDTH = 10
window.GAME_SCORE_HEIGHT = 30
window.GAME_PAUSE_BUTTON_WIDTH = 32
window.GAME_PAUSE_BUTTON_HEIGHT = window.GAME_PAUSE_BUTTON_WIDTH
window.GAME_PAUSE_BUTTON_X = CANVAS_WIDTH - GAME_SCORE_X - GAME_PAUSE_BUTTON_WIDTH




window.RANDOM_PLANE_WIDTH = 60
window.RANDOM_PLANE_HEIGHT = 20
window.RANDOM_PLANE_SPEED = 250
window.RANDOM_PLANE_TRAIL_LENGTH = Math.floor(CANVAS_WIDTH * 0.3)
window.RANDOM_PLANE_TRAIL_THICKNESS = 1
window.RANDOM_PLANE_MIN_Y = Math.floor(SCREEN_HEIGHT * 0.02)
window.RANDOM_PLANE_MAX_Y = Math.floor(SCREEN_HEIGHT * 0.35)
window.RANDOM_PLANE_MIN_X = Math.floor(CANVAS_WIDTH * 1.2)
window.RANDOM_PLANE_MAX_X = Math.floor(CANVAS_WIDTH * 6)



window.BODY_FONT = "bold 18pt Arial"
window.GAME_OVERLAY_TITLE_FONT = "bold 36pt Arial"


window.MAIN_TITLE_X = CANVAS_WIDTH * 0.78
window.MAIN_TITLE_Y = CANVAS_HEIGHT * 0.18
window.MAIN_TITLE_ANGLE = Math.PI / 8
window.MAIN_TITLE_EXTRA_WIDTH = 10
window.MAIN_TITLE_HEIGHT = 60
window.MAIN_PLAY_BOX_X = CANVAS_WIDTH * 0.64
window.MAIN_PLAY_BOX_Y = CANVAS_HEIGHT * 0.67
window.MAIN_PLAY_BOX_WIDTH = CANVAS_WIDTH * 0.34
window.MAIN_PLAY_BOX_HEIGHT = CANVAS_HEIGHT * 0.3



window.GAME_OVERLAY_X = CANVAS_WIDTH * 0.15
window.GAME_OVERLAY_Y = CANVAS_HEIGHT * 0.1
window.GAME_OVERLAY_WIDTH = CANVAS_WIDTH * 0.7
window.GAME_OVERLAY_HEIGHT = CANVAS_HEIGHT * 0.8
window.GAME_OVERLAY_TITLE_TEXT_X = CANVAS_WIDTH * 0.5
window.GAME_OVERLAY_TITLE_TEXT_Y = CANVAS_HEIGHT * 0.18
window.GAME_OVERLAY_BODY_TEXT_X = CANVAS_WIDTH * 0.5
window.GAME_OVERLAY_BODY_TEXT_Y = CANVAS_HEIGHT * 0.4
window.GAME_OVERLAY_BUTTON_MARGIN = GAME_OVERLAY_WIDTH * 0.02
window.GAME_OVERLAY_BUTTON_WIDTH = (GAME_OVERLAY_WIDTH - (4 * GAME_OVERLAY_BUTTON_MARGIN)) / 2
window.GAME_OVERLAY_BUTTON_HEIGHT = 40



window.SAVE_SEPERATOR = "|"
window.SAVE_HIGHSCORE_TITLE = "HIGHSCORES"
window.SAVE_HIGHSCORE_COUNT = 8
window.SAVE_LAST_NAME_TITLE = "LAST_NAME"