// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.HelpScreen = (function(_super) {
    __extends(HelpScreen, _super);

    function HelpScreen() {
      this.menuButton = new Button({
        x: GAME_OVERLAY_X + GAME_OVERLAY_BUTTON_MARGIN,
        y: GAME_OVERLAY_Y + GAME_OVERLAY_HEIGHT - GAME_OVERLAY_BUTTON_MARGIN - GAME_OVERLAY_BUTTON_HEIGHT,
        width: GAME_OVERLAY_BUTTON_WIDTH,
        height: GAME_OVERLAY_BUTTON_HEIGHT,
        text: "Menu",
        hoveredText: "> Menu <"
      });
    }

    HelpScreen.prototype.update = function(deltaTime) {
      this.menuButton.update(deltaTime);
      if (this.menuButton.clicked) {
        changeScreen(new MainMenuScreen());
      }
    };

    HelpScreen.prototype.render = function(context) {
      context.drawImage(backgroundCanvas, 0, 0);
      return this.menuButton.render(context);
    };

    return HelpScreen;

  })(Screen);

}).call(this);
