// Generated by CoffeeScript 1.7.1
(function() {
  window.Screen = (function() {
    function Screen() {}

    Screen.prototype.update = function(deltaTime) {};

    Screen.prototype.render = function(context) {};

    Screen.prototype.close = function() {};

    return Screen;

  })();

}).call(this);
