// Generated by CoffeeScript 1.7.1
(function() {
  var context, deltaTime, lastTime, main, now, screen;

  if (typeof String.prototype.startsWith !== "function") {
    String.prototype.startsWith = function(prefix) {
      return this.indexOf(prefix) === 0;
    };
  }

  if (typeof String.prototype.endsWith !== "function") {
    String.prototype.endsWith = function(suffix) {
      return this.indexOf(suffix, this.length - suffix.length) !== -1;
    };
  }

  window.canvas = null;

  context = null;

  screen = null;

  window.changeScreen = function(newScreen) {
    if (screen != null) {
      screen.close();
    }
    screen = newScreen;
    cleanKeys();
    updateKeys();
    return updateMouse();
  };

  lastTime = Date.now();

  now = Date.now();

  deltaTime = 0;

  main = function() {
    window.requestAnimFrame(main);
    now = Date.now();
    deltaTime = (now - lastTime) / 1000.0;
    screen.update(deltaTime);
    screen.render(context);
    updateKeys();
    updateMouse();
    return lastTime = now;
  };

  window.onload = function() {
    window.canvas = createCanvas(CANVAS_WIDTH, CANVAS_HEIGHT);
    document.body.appendChild(canvas);
    canvas.setAttribute("tabindex", "1");
    canvas.focus();
    canvas.onkeydown = onKeyDown;
    canvas.onkeyup = onKeyUp;
    canvas.onmousedown = onMouseDown;
    canvas.onmousemove = onMouseMove;
    canvas.onmouseup = onMouseUp;
    context = canvas.getContext("2d");
    createPlayerCanvas();
    createBackgroundCanvas(Math.random() < DAYTIME_CHANCE);
    createPlaneCanvas();
    changeScreen(new MainMenuScreen());
    lastTime = Date.now();
    return main();
  };

}).call(this);
