// Generated by CoffeeScript 1.7.1
(function() {
  window.requestAnimFrame = (function() {
    return window.requestAnimationFrame || window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame || window.oRequestAnimationFrame || window.msRequestAnimationFrame || function(callback) {
      return setTimout(callback, 1000 / 60);
    };
  })();

  window.randomNumberExclusive = function(lower, upper) {
    if (lower == null) {
      lower = 0;
    }
    if (upper == null) {
      upper = 1;
    }
    return Math.floor(Math.random() * (upper - lower)) + lower;
  };

  window.randomNumberInclusive = function(lower, upper) {
    if (lower == null) {
      lower = 0;
    }
    if (upper == null) {
      upper = 1;
    }
    return Math.floor(Math.random() * (upper + 1 - lower)) + lower;
  };

  window.setCanvasSize = function(canvas, width, height) {
    if (width == null) {
      width = 0;
    }
    if (height == null) {
      height = 0;
    }
    canvas.width = width;
    canvas.height = height;
    return canvas;
  };

  window.createCanvas = function(width, height) {
    if (width == null) {
      width = 0;
    }
    if (height == null) {
      height = 0;
    }
    return setCanvasSize(document.createElement("canvas"), width, height);
  };

}).call(this);
